name: Retry Failed Posts

on:

  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:

  retry:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - name: Retry Posts
        run: node retry/retry-engine.js
``
